import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './styles/reset.scss'
import './styles/globals.scss'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Positivus',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={spaceGrotesk.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
